
const conf = {
    nv: {}
} 

function initConfiguration(configuration) {
    conf.nv.user = configuration.nv_user;
    conf.nv.pwd = configuration.nv_pwd;
    conf.nv.connectString = configuration.nv_connect;
}

const PROPSQL =
    `SELECT (PROP_ORGS_CUSTODIAN.PRIMARY_CONTACT_FULL_NM), --PCO
        PROP_LOCATIONS_DIM.LOCATION_FULL_STR, -- Current Location
        (HR_PROP_WRKF_SUPERVISOR.FULL_NAME) SUPERVISOR_FULL_NAME, -- Supervisor
        PROP_INTEREST_ASSETS_DIM.PATIENT_CARE_FLG, -- Patient Care Flag
        PROP_ORGS_CUSTODIAN.PRIMARY_CONTACT_LOCATION, -- PCO Location
        HR_PROP_WRKF_ACCTBLE_USER.FULL_LOCATION || ', USA' ACCTBLE_USER_FULL_LOCATION, -- User Location
        HR_PROP_WRKF_SUPERVISOR.FULL_LOCATION || ', USA' SUPERVISOR_FULL_LOCATION, -- Supervisor Location  
        (PROP_CATALOG_DIM.OFFICIAL_NM),
        HR_PROP_WRKF_ACCTBLE_USER.WRKF_KEY,
        PROP_ASSET_VALUE_FCT.SUPERVISOR_WRKF_KEY,
        PROP_ASSET_VALUE_FCT.CURRENT_FLG,
        PROP_ASSET_VALUE_FCT.ASSET_VALUE_KEY,
        PROP_ASSET_VALUE_FCT.ASSET_KEY,
--         PROP_ASSETS_DIM.ASSET_KEY,
--         PROP_APPROPRIATION_CD_MV.ASSET_VALUE_KEY,
        PROP_INTEREST_ASSETS_DIM.INTEREST_ASSET_KEY,
        PROP_ASSET_VALUE_FCT.INITIAL_EVENT_KEY,
        PROP_EVENT_INIT_EVENTS.EVENT_KEY,
        PROP_ASSETS_DIM.ACTIVITY_STATUS_DESC,
        (PROP_CATALOG_DIM.ASSET_TYP_CD),
        (PROP_ORGS_CUSTODIAN.IC_CD),
        (PROP_ORGS_CUSTODIAN.ORG_CD),
        (PROP_CATALOG_DIM.MANUFACTURER_NM),
        (PROP_CATALOG_DIM.MODEL_NBR),
        TRIM (PROP_ASSETS_DIM.SERIAL_NBR) SERIAL_NBR,
        (HR_PROP_WRKF_ACCTBLE_USER.FULL_NAME),
        (HR_PROP_WRKF_ACCTBLE_USER.CURR_NED_ID),
        (HR_PROP_WRKF_ACCTBLE_USER.ORIG_NED_ID),
        PROP_EVENT_INIT_EVENTS.PO_NBR,
        PROP_ASSETS_DIM.ACQUISITION_DT,
        PROP_ASSETS_DIM.LAST_INVENTORY_DT,
        PROP_CATALOG_DIM.SENSITIVE_FLG,
        PROP_CATALOG_DIM.ASSET_TYP_DESC,
        PROP_ASSET_VALUE_FCT.ACQUISITION_COST,
        PROP_ASSETS_DIM.AGRMNT_ID,
        PROP_ASSETS_DIM.LAST_INVENTORY_RESOLUTION,
        PROP_ASSETS_DIM.UNCAPITALIZED_REASON_CD,
        PROP_ASSETS_DIM.UNCAPITALIZED_REASON_DESC,
        PROP_ASSETS_DIM.ASSET_CONDITION_CD || ' - ' || PROP_ASSETS_DIM.ASSET_CONDITION_DESC CONDITION_DESC,
        (PROP_EVENT_INIT_EVENTS.EVENT_DT),
        (PROP_EVENT_INIT_EVENTS.EVENT_TYP_DESC),
        PROP_INTEREST_ASSETS_DIM.PERSONAL_CUSTODY_FLG,
        PROP_CATALOG_DIM.SERVICE_LIFE,
        PROP_ASSETS_DIM.ASSET_DECAL_NBR,
        PROP_ASSETS_DIM.CAPITAL_FLG,
        PROP_APPROPRIATION_CD_MV.APPROPRIATION_CD,
        PROP_ASSET_VALUE_FCT.ACCUMULATED_DEPRECIATION,
        PROP_ASSET_VALUE_FCT.MONTHLY_DEPRECIATION,
        PROP_ASSET_VALUE_FCT.YTD_DEPRECIATION,
        PROP_ASSET_VALUE_FCT.ASSET_VALUE_TOTAL
        - NVL (PROP_ASSET_VALUE_FCT.ACCUMULATED_DEPRECIATION, 0) ASSET_VALUE,
        PROP_ASSETS_DIM.OTHER_USER,
        PROP_ASSETS_DIM.OLD_ASSET_ID,
        PROP_ASSETS_DIM.RESPONSIBILITY_BEGIN_DT,
        PROP_INTEREST_ASSETS_DIM.NON_STANDARD_DESC,
        PROP_INTEREST_ASSETS_DIM.WARRANTY_EXPIRATION_DT,
        (PROP_LOCATIONS_DIM.OFFSITE_DESC) LOCATION_OFFSITE_DESC, -- choices: null, GENERAL OFF SITE FOR HVS, OFFSITE, HOME USE, OFF SITE LOCATION, OFFSIT
        (PROP_LOCATIONS_DIM.ADDRESS_LINE_1) LOCATION_ADDRESS_LINE_1,
        (PROP_LOCATIONS_DIM.ADDRESS_LINE_2) LOCATION_ADDRESS_LINE_2,
        (PROP_LOCATIONS_DIM.ADDRESS_LINE_3) LOCATION_ADDRESS_LINE_3,
        (PROP_LOCATIONS_DIM.CITY_NM) LOCATION_CITY_NM,
        (PROP_LOCATIONS_DIM.STATE_CD) LOCATION_STATE_CD,
        (PROP_LOCATIONS_DIM.STATE_NM) LOCATION_STATE_NM,
        (PROP_LOCATIONS_DIM.COUNTRY_NM) LOCATION_COUNTRY_NM,
        (PROP_LOCATIONS_DIM.COUNTY_NM) LOCATION_COUNTY_NM,
        (PROP_LOCATIONS_DIM.POSTAL_CD) LOCATION_POSTAL_CD,
        PROP_ASSETS_DIM.FLAG_1
     FROM PROP_CATALOG_DIM,
          PROP_ASSET_VALUE_FCT,
          PROP_ASSETS_DIM,
          HR_WRKF_GEN_DIM HR_PROP_WRKF_ACCTBLE_USER,
          PROP_ORG_DIM PROP_ORGS_CUSTODIAN,
          PROP_INTEREST_ASSETS_DIM,
          PROP_EVENTS_DIM PROP_EVENT_INIT_EVENTS,
          PROP_LOCATIONS_DIM,
          HR_WRKF_GEN_DIM HR_PROP_WRKF_SUPERVISOR,
          PROP_APPROPRIATION_CD_MV
     WHERE (PROP_ASSET_VALUE_FCT.INTEREST_ASSET_KEY = PROP_INTEREST_ASSETS_DIM.INTEREST_ASSET_KEY)
        AND (PROP_ASSETS_DIM.ASSET_KEY = PROP_ASSET_VALUE_FCT.ASSET_KEY)
        AND (HR_PROP_WRKF_SUPERVISOR.WRKF_KEY = PROP_ASSET_VALUE_FCT.SUPERVISOR_WRKF_KEY)
        AND (HR_PROP_WRKF_ACCTBLE_USER.WRKF_KEY =
                    PROP_ASSET_VALUE_FCT.USER_WRKF_KEY)
        AND (PROP_CATALOG_DIM.CATALOG_KEY = PROP_ASSET_VALUE_FCT.CATALOG_KEY)
        AND (PROP_LOCATIONS_DIM.LOCATION_KEY =
                    PROP_ASSET_VALUE_FCT.LOCATION_KEY)
        AND (PROP_ORGS_CUSTODIAN.ORG_KEY =
                    PROP_ASSET_VALUE_FCT.STEWARD_ORG_KEY)
        AND (PROP_ASSET_VALUE_FCT.INITIAL_EVENT_KEY =
                    PROP_EVENT_INIT_EVENTS.EVENT_KEY)
        AND (PROP_ASSET_VALUE_FCT.ASSET_VALUE_KEY =
                    PROP_APPROPRIATION_CD_MV.ASSET_VALUE_KEY)
        AND (PROP_ORGS_CUSTODIAN.ORG_TYP_CD = ('STEW'))
        AND PROP_INTEREST_ASSETS_DIM.INTEREST_TYP = ('INVENTORY ASSET')
        AND PROP_ASSET_VALUE_FCT.CURRENT_FLG = 'Y'
        AND PROP_ASSETS_DIM.ACTIVITY_STATUS_DESC IN ('EXCESS',
                                                     'IN SERVICE',
                                                     'ON LOAN',
                                                     'ON PASS',
                                                     'ON REPAIR PASS')
        AND PROP_ORGS_CUSTODIAN.IC_CD = 'NCI'`


module.exports = { initConfiguration, conf, PROPSQL }
