AWSTemplateFormatVersion: "2010-09-09"
Description: Create a web server ec2 instance with security group
Parameters:
  VpcId:
    Description: Current VPC Id
    Type: String
  SubnetId:
    Description: Subnet ID for EC2 instance
    Type: String
  VPCEndpointGroupId:
    Description: Security Group Id for VPC endpoint
    Type: String

Resources:
  VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: '*'
            Resource: '*'
      PrivateDnsEnabled: true
      VpcEndpointType: Interface
      SecurityGroupIds:
        - !Ref VPCEndpointGroupId
      ServiceName: com.amazonaws.us-east-1.execute-api
      VpcId: !Ref VpcId
      SubnetIds:
        - !Ref SubnetId

Outputs:
  VPCEndpointId:
    Description: VPC Endpoint Id
    Value: !Ref VpcEndpoint
