/**
 * User REST Web Service API
 * Enterprise Data & Integration Services Web Services - **NED REST Web Service**
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: NCICBIITBizAppsSupportLowTier@mail.nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class NEDChangeRecord {
    'nIHSITE'?: string;
    'aCTIONDATE'?: string;
    'aCTION'?: string;
    'uNIQUEIDENTIFIER'?: string;
    'aCTIONTIME'?: string;
    'sN'?: string;
    'nIHORGACRONYM'?: string;
    'gIVENNAME'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nIHSITE",
            "baseName": "NIHSITE",
            "type": "string"
        },
        {
            "name": "aCTIONDATE",
            "baseName": "ACTION_DATE",
            "type": "string"
        },
        {
            "name": "aCTION",
            "baseName": "ACTION",
            "type": "string"
        },
        {
            "name": "uNIQUEIDENTIFIER",
            "baseName": "UNIQUEIDENTIFIER",
            "type": "string"
        },
        {
            "name": "aCTIONTIME",
            "baseName": "ACTION_TIME",
            "type": "string"
        },
        {
            "name": "sN",
            "baseName": "SN",
            "type": "string"
        },
        {
            "name": "nIHORGACRONYM",
            "baseName": "NIHORGACRONYM",
            "type": "string"
        },
        {
            "name": "gIVENNAME",
            "baseName": "GIVENNAME",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NEDChangeRecord.attributeTypeMap;
    }
}

