/**
 * User REST Web Service API
 * Enterprise Data & Integration Services Web Services - **NED REST Web Service**
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: NCICBIITBizAppsSupportLowTier@mail.nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class NEDChangeRecord {
    public NIHSITE?: string;
    public ACTIONDATE?: string;
    public ACTION?: string;
    public UNIQUEIDENTIFIER?: string;
    public ACTIONTIME?: string;
    public SN?: string;
    public NIHORGACRONYM?: string;
    public GIVENNAME?: string;
 
    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nIHSITE",
            "baseName": "NIHSITE",
            "type": "string"
        },
        {
            "name": "aCTIONDATE",
            "baseName": "ACTION_DATE",
            "type": "string"
        },
        {
            "name": "aCTION",
            "baseName": "ACTION",
            "type": "string"
        },
        {
            "name": "uNIQUEIDENTIFIER",
            "baseName": "UNIQUEIDENTIFIER",
            "type": "string"
        },
        {
            "name": "aCTIONTIME",
            "baseName": "ACTION_TIME",
            "type": "string"
        },
        {
            "name": "sN",
            "baseName": "SN",
            "type": "string"
        },
        {
            "name": "nIHORGACRONYM",
            "baseName": "NIHORGACRONYM",
            "type": "string"
        },
        {
            "name": "gIVENNAME",
            "baseName": "GIVENNAME",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return NEDChangeRecord.attributeTypeMap;
    }

    public static example(): NEDChangeRecord {
        let r = new NEDChangeRecord()
        r.NIHSITE = 'MD-BC'
        r.ACTIONDATE = '2022-08-01'
        r.ACTION = 'modified'
        r.UNIQUEIDENTIFIER = '1234567890'
        r.ACTIONTIME = '00:01:01'
        r.SN = 'Smith'
        r.NIHORGACRONYM = 'NCI'
        r.GIVENNAME = 'MIKE'
        return r
    }
}

