/**
 * User REST Web Service API
 * Enterprise Data & Integration Services Web Services - **NED REST Web Service**
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: NCICBIITBizAppsSupportLowTier@mail.nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class VDSUser {
    'uNIQUEIDENTIFIER'?: string;
    'nIHDUPUID'?: string;
    'nIHADACCTREQ'?: string;
    'nIHSSOUSERNAME'?: string;
    'distinguishedName'?: string;
    'nIHADMAILBOXREQ'?: string;
    'nIHPRIMARYSMTP'?: string;
    'mAIL'?: string;
    'proxyAddresses'?: Array<string>;
    'displayName'?: string;
    'pERSONALTITLE'?: string;
    'gIVENNAME'?: string;
    'nIHCOMMONGIVENNAME'?: string;
    'nIHNOMIDDLENAME'?: string;
    'mIDDLENAME'?: string;
    'nIHCOMMONMIDDLENAM'?: string;
    'nIHMIXCASESN'?: string;
    'nIHMIXCASECOMMONSN'?: string;
    'sN'?: string;
    'nIHCOMMONSN'?: string;
    'gENERATIONQUALIF'?: string;
    'nIHCOMMONGENQUALIF'?: string;
    'nIHSUFFIXQUALIFIER'?: string;
    'tITLE'?: string;
    'nIHIPD'?: string;
    'nIHBADGETITLE'?: string;
    'nIHIDBADGEEXPDATE'?: string;
    'nIHSAC'?: string;
    'nIHPrivacyAwarenessCompDate'?: string;
    'privacyAwarenessRefresherCompDate'?: string;
    'nIHInformationSecurityAwarenessCompDate'?: string;
    'informationSecurityRefresherCompDate'?: string;
    'description'?: string;
    'oRGANIZATIONALSTAT'?: string;
    'nIHSUBORGSTATUS'?: string;
    'nIHSUMMERSTATUS'?: string;
    'nIHORGPATH'?: string;
    'nIHPHYSICALADDRESS'?: string;
    'nIHORGACRONYM'?: string;
    'nIHSERVAO'?: string;
    'mANAGER'?: string;
    'nIHCOTRID'?: string;
    'nIHPOC'?: string;
    'nIHCOMPANYNAME'?: string;
    'nIHCOMPANYPHONE'?: string;
    'countryCode'?: string;
    'tELEPHONENUMBER'?: string;
    'mOBILETELEPHONENUM'?: string;
    'mobile'?: string;
    'ipPhone'?: string;
    'nIHSITE'?: string;
    'l'?: string;
    'bUILDINGNAME'?: string;
    'rOOMNUMBER'?: string;
    'pOSTALADDRESS'?: string;
    'nIHIDBADGELESS6MOS'?: string;
    'managedObjects'?: string;
    'memberOf'?: Array<string>;
    'nIHCREATETIMESTAMP'?: string;
    'nIHMODIFYTIMESTAMP'?: string;
    'nIHMODIFIERSNAME'?: string;
    'nIHDIRENTRYEFFECTIVEDATE'?: string;
    'nIHDIRENTRYEXPIRATIONDATE'?: string;
    'userAccountControl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "uNIQUEIDENTIFIER",
            "baseName": "UNIQUEIDENTIFIER",
            "type": "string"
        },
        {
            "name": "nIHDUPUID",
            "baseName": "NIHDUPUID",
            "type": "string"
        },
        {
            "name": "nIHADACCTREQ",
            "baseName": "NIHADACCTREQ",
            "type": "string"
        },
        {
            "name": "nIHSSOUSERNAME",
            "baseName": "NIHSSOUSERNAME",
            "type": "string"
        },
        {
            "name": "distinguishedName",
            "baseName": "distinguishedName",
            "type": "string"
        },
        {
            "name": "nIHADMAILBOXREQ",
            "baseName": "NIHADMAILBOXREQ",
            "type": "string"
        },
        {
            "name": "nIHPRIMARYSMTP",
            "baseName": "NIHPRIMARYSMTP",
            "type": "string"
        },
        {
            "name": "mAIL",
            "baseName": "MAIL",
            "type": "string"
        },
        {
            "name": "proxyAddresses",
            "baseName": "proxyAddresses",
            "type": "Array<string>"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "pERSONALTITLE",
            "baseName": "PERSONALTITLE",
            "type": "string"
        },
        {
            "name": "gIVENNAME",
            "baseName": "GIVENNAME",
            "type": "string"
        },
        {
            "name": "nIHCOMMONGIVENNAME",
            "baseName": "NIHCOMMONGIVENNAME",
            "type": "string"
        },
        {
            "name": "nIHNOMIDDLENAME",
            "baseName": "NIHNOMIDDLENAME",
            "type": "string"
        },
        {
            "name": "mIDDLENAME",
            "baseName": "MIDDLENAME",
            "type": "string"
        },
        {
            "name": "nIHCOMMONMIDDLENAM",
            "baseName": "NIHCOMMONMIDDLENAM",
            "type": "string"
        },
        {
            "name": "nIHMIXCASESN",
            "baseName": "NIHMIXCASESN",
            "type": "string"
        },
        {
            "name": "nIHMIXCASECOMMONSN",
            "baseName": "NIHMIXCASECOMMONSN",
            "type": "string"
        },
        {
            "name": "sN",
            "baseName": "SN",
            "type": "string"
        },
        {
            "name": "nIHCOMMONSN",
            "baseName": "NIHCOMMONSN",
            "type": "string"
        },
        {
            "name": "gENERATIONQUALIF",
            "baseName": "GENERATIONQUALIF",
            "type": "string"
        },
        {
            "name": "nIHCOMMONGENQUALIF",
            "baseName": "NIHCOMMONGENQUALIF",
            "type": "string"
        },
        {
            "name": "nIHSUFFIXQUALIFIER",
            "baseName": "NIHSUFFIXQUALIFIER",
            "type": "string"
        },
        {
            "name": "tITLE",
            "baseName": "TITLE",
            "type": "string"
        },
        {
            "name": "nIHIPD",
            "baseName": "NIHIPD",
            "type": "string"
        },
        {
            "name": "nIHBADGETITLE",
            "baseName": "NIHBADGETITLE",
            "type": "string"
        },
        {
            "name": "nIHIDBADGEEXPDATE",
            "baseName": "NIHIDBADGEEXPDATE",
            "type": "string"
        },
        {
            "name": "nIHSAC",
            "baseName": "NIHSAC",
            "type": "string"
        },
        {
            "name": "nIHPrivacyAwarenessCompDate",
            "baseName": "NIHPrivacyAwarenessCompDate",
            "type": "string"
        },
        {
            "name": "privacyAwarenessRefresherCompDate",
            "baseName": "PrivacyAwarenessRefresherCompDate",
            "type": "string"
        },
        {
            "name": "nIHInformationSecurityAwarenessCompDate",
            "baseName": "NIHInformationSecurityAwarenessCompDate",
            "type": "string"
        },
        {
            "name": "informationSecurityRefresherCompDate",
            "baseName": "InformationSecurityRefresherCompDate",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "oRGANIZATIONALSTAT",
            "baseName": "ORGANIZATIONALSTAT",
            "type": "string"
        },
        {
            "name": "nIHSUBORGSTATUS",
            "baseName": "NIHSUBORGSTATUS",
            "type": "string"
        },
        {
            "name": "nIHSUMMERSTATUS",
            "baseName": "NIHSUMMERSTATUS",
            "type": "string"
        },
        {
            "name": "nIHORGPATH",
            "baseName": "NIHORGPATH",
            "type": "string"
        },
        {
            "name": "nIHPHYSICALADDRESS",
            "baseName": "NIHPHYSICALADDRESS",
            "type": "string"
        },
        {
            "name": "nIHORGACRONYM",
            "baseName": "NIHORGACRONYM",
            "type": "string"
        },
        {
            "name": "nIHSERVAO",
            "baseName": "NIHSERVAO",
            "type": "string"
        },
        {
            "name": "mANAGER",
            "baseName": "MANAGER",
            "type": "string"
        },
        {
            "name": "nIHCOTRID",
            "baseName": "NIHCOTRID",
            "type": "string"
        },
        {
            "name": "nIHPOC",
            "baseName": "NIHPOC",
            "type": "string"
        },
        {
            "name": "nIHCOMPANYNAME",
            "baseName": "NIHCOMPANYNAME",
            "type": "string"
        },
        {
            "name": "nIHCOMPANYPHONE",
            "baseName": "NIHCOMPANYPHONE",
            "type": "string"
        },
        {
            "name": "countryCode",
            "baseName": "countryCode",
            "type": "string"
        },
        {
            "name": "tELEPHONENUMBER",
            "baseName": "TELEPHONENUMBER",
            "type": "string"
        },
        {
            "name": "mOBILETELEPHONENUM",
            "baseName": "MOBILETELEPHONENUM",
            "type": "string"
        },
        {
            "name": "mobile",
            "baseName": "mobile",
            "type": "string"
        },
        {
            "name": "ipPhone",
            "baseName": "ipPhone",
            "type": "string"
        },
        {
            "name": "nIHSITE",
            "baseName": "NIHSITE",
            "type": "string"
        },
        {
            "name": "l",
            "baseName": "L",
            "type": "string"
        },
        {
            "name": "bUILDINGNAME",
            "baseName": "BUILDINGNAME",
            "type": "string"
        },
        {
            "name": "rOOMNUMBER",
            "baseName": "ROOMNUMBER",
            "type": "string"
        },
        {
            "name": "pOSTALADDRESS",
            "baseName": "POSTALADDRESS",
            "type": "string"
        },
        {
            "name": "nIHIDBADGELESS6MOS",
            "baseName": "NIHIDBADGELESS6MOS",
            "type": "string"
        },
        {
            "name": "managedObjects",
            "baseName": "managedObjects",
            "type": "string"
        },
        {
            "name": "memberOf",
            "baseName": "memberOf",
            "type": "Array<string>"
        },
        {
            "name": "nIHCREATETIMESTAMP",
            "baseName": "NIHCREATETIMESTAMP",
            "type": "string"
        },
        {
            "name": "nIHMODIFYTIMESTAMP",
            "baseName": "NIHMODIFYTIMESTAMP",
            "type": "string"
        },
        {
            "name": "nIHMODIFIERSNAME",
            "baseName": "NIHMODIFIERSNAME",
            "type": "string"
        },
        {
            "name": "nIHDIRENTRYEFFECTIVEDATE",
            "baseName": "NIHDIRENTRYEFFECTIVEDATE",
            "type": "string"
        },
        {
            "name": "nIHDIRENTRYEXPIRATIONDATE",
            "baseName": "NIHDIRENTRYEXPIRATIONDATE",
            "type": "string"
        },
        {
            "name": "userAccountControl",
            "baseName": "userAccountControl",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return VDSUser.attributeTypeMap;
    }
}

