openapi: 3.0.0
info:
  description: Enterprise Data & Integration Services Web Services - **NED REST Web Service**
  version: "0.1.0"
  title: User REST Web Service API
  # put the contact info for your development or API team
  contact:
    email: NCICBIITBizAppsSupportLowTier@mail.nih.gov
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params:
    validateRequestBody: true
    validateRequestParameters: true
  body:
    validateRequestBody: true
    validateRequestParameters: false

# tags are used for organizing operations
tags:
  - name: clients
    description: Operations available to clients - service to service

paths:
  /userapi/vds/userById/{id}:
    get:
      tags:
        - clients
      summary: Get VDS User record by the given NIH id (UNIQUEIDENTIFIER)
      operationId: getVDSUserByNIHId
      description: |
        Get VDS User record(s) that satisfied NIH ID criteria
      parameters:
        - name: id
          in: path
          required: true
          description: user NIH ID
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/vdsresponse'
      x-amazon-apigateway-integration:
        uri: ${lambda_invoke_arn}
        httpMethod: POST
        timeoutInMillis: 29000
        type: aws_proxy

  /userapi/vds/usersByIc/{ic}:
    get:
      tags:
        - clients
      summary: List VDS user records by the given IC
      operationId: listVDSUsersByIC
      description: |
        Get VDS user records that satisfied IC criteria
      parameters: 
        - name: ic
          in: path
          description: IC
          required: true
          schema:
            type: string
            example: 'NCI'
        - name: lastEvaluatedKey
          in: query
          description: Last Evaluated Key from previous request
          required: false
          schema:
            type: string
            example: '12345'
      responses:
        '200':
          $ref: '#/components/responses/vdsUsersByIcResponse'
      x-amazon-apigateway-integration:
        type: aws
        httpMethod: POST
        uri: ${ddb_action_query}
        credentials: ${ddb_role_arn}
        timeoutInMillis: 29000
        passthroughBehavior: when_no_templates
        cacheKeyParameters:
          - method.request.path.ic
          - method.request.querystring.lastEvaluatedKey
        requestTemplates:
          application/json: |-
            #set($ic = $input.params('ic'))
            #set($lastEvaluatedKey = $input.params('lastEvaluatedKey'))
            {
              "TableName": "${users_table_name}",
              "IndexName": "icIndex",
              "KeyConditionExpression": "NIHORGACRONYM = :ic",
              "ExpressionAttributeValues": {
                ":ic": { "S": "$ic" }
              }
            #if($lastEvaluatedKey != "")
              , "ExclusiveStartKey": { "NEDId": { "S": "$lastEvaluatedKey" }, "NIHORGACRONYM": { "S": "$ic" } }
            #end
            }
        responses:
          2\d{2}:
            statusCode: 200
            responseTemplates:
              application/json: |-
                #set ($inputRoot = $input.path('$'))
                #set ($lastEvaluatedKey = $inputRoot.LastEvaluatedKey.NEDId.S)
                {
                  "count": $inputRoot.Count,
                #if($lastEvaluatedKey != "")
                  "lastEvaluatedKey": "$lastEvaluatedKey",
                #end
                  "items": [
                #foreach($elem in $inputRoot.Items)
                    {
                      "UNIQUEIDENTIFIER": "$elem.UNIQUEIDENTIFIER.S",
                      "NIHDUPUID": "$elem.NIHDUPUID.S",
                      "NIHADACCTREQ": "$elem.NIHADACCTREQ.S",
                      "NIHSSOUSERNAME": "$elem.NIHSSOUSERNAME.S",
                      "distinguishedName": "$elem.distinguishedName.S",
                      "NIHADMAILBOXREQ": "$elem.NIHADMAILBOXREQ.S",
                      "NIHPRIMARYSMTP": "$elem.NIHPRIMARYSMTP.S",
                      "MAIL": "$elem.MAIL.S",
                      "proxyAddresses": "$elem.proxyAddresses.SS",
                      "displayName": "$elem.displayName.S",
                      "PERSONALTITLE": "$elem.PERSONALTITLE.S",
                      "GIVENNAME": "$elem.GIVENNAME.S",
                      "NIHCOMMONGIVENNAME": "$elem.NIHCOMMONGIVENNAME.S",
                      "NIHNOMIDDLENAME": "$elem.NIHNOMIDDLENAME.S",
                      "MIDDLENAME": "$elem.MIDDLENAME.S",
                      "NIHCOMMONMIDDLENAM": "$elem.NIHCOMMONMIDDLENAM.S",
                      "NIHMIXCASESN": "$elem.NIHMIXCASESN.S",
                      "NIHMIXCASECOMMONSN": "$elem.NIHMIXCASECOMMONSN.S",
                      "SN": "$elem.SN.S",
                      "NIHCOMMONSN": "$elem.NIHCOMMONSN.S",
                      "GENERATIONQUALIF": "$elem.GENERATIONQUALIF.S",
                      "NIHCOMMONGENQUALIF": "$elem.NIHCOMMONGENQUALIF.S",
                      "NIHSUFFIXQUALIFIER": "$elem.NIHSUFFIXQUALIFIER.S",
                      "TITLE": "$elem.TITLE.S",
                      "NIHIPD": "$elem.NIHIPD.S",
                      "NIHBADGETITLE": "$elem.NIHBADGETITLE.S",
                      "NIHIDBADGEEXPDATE": "$elem.NIHIDBADGEEXPDATE.S",
                      "NIHSAC": "$elem.NIHSAC.S",
                      "NIHPrivacyAwarenessCompDate": "$elem.NIHPrivacyAwarenessCompDate.S",
                      "PrivacyAwarenessRefresherCompDate": "$elem.PrivacyAwarenessRefresherCompDate.S",
                      "NIHInformationSecurityAwarenessCompDate": "$elem.NIHInformationSecurityAwarenessCompDate.S",
                      "InformationSecurityRefresherCompDate": "$elem.InformationSecurityRefresherCompDate.S",
                      "description": "$elem.description.S",
                      "ORGANIZATIONALSTAT": "$elem.ORGANIZATIONALSTAT.S",
                      "NIHSUBORGSTATUS": "$elem.NIHSUBORGSTATUS.S",
                      "NIHSUMMERSTATUS": "$elem.NIHSUMMERSTATUS.S",
                      "NIHORGPATH": "$elem.NIHORGPATH.S",
                      "NIHPHYSICALADDRESS": "$elem.NIHPHYSICALADDRESS.S",
                      "NIHORGACRONYM": "$elem.NIHORGACRONYM.S",
                      "NIHSERVAO": "$elem.NIHSERVAO.S",
                      "MANAGER": "$elem.MANAGER.S",
                      "NIHCOTRID": "$elem.NIHCOTRID.S",
                      "NIHPOC": "$elem.NIHPOC.S",
                      "NIHCOMPANYNAME": "$elem.NIHCOMPANYNAME.S",
                      "NIHCOMPANYPHONE": "$elem.NIHCOMPANYPHONE.S",
                      "countryCode": "$elem.countryCode.S",
                      "TELEPHONENUMBER": "$elem.TELEPHONENUMBER.S",
                      "MOBILETELEPHONENUM": "$elem.MOBILETELEPHONENUM.S",
                      "mobile": "$elem.mobile.S",
                      "ipPhone": "$elem.ipPhone.S",
                      "NIHSITE": "$elem.NIHSITE.S",
                      "L": "$elem.L.S",
                      "BUILDINGNAME": "$elem.BUILDINGNAME.S",
                      "ROOMNUMBER": "$elem.ROOMNUMBER.S",
                      "POSTALADDRESS": "$elem.POSTALADDRESS.S",
                      "NIHIDBADGELESS6MOS": "$elem.NIHIDBADGELESS6MOS.S",
                      "managedObjects": "$elem.managedObjects.S",
                      "memberOf": "$elem.memberOf.SS",
                      "NIHCREATETIMESTAMP": "$elem.NIHCREATETIMESTAMP.S",
                      "NIHMODIFYTIMESTAMP": "$elem.NIHMODIFYTIMESTAMP.S",
                      "NIHMODIFIERSNAME": "$elem.NIHMODIFIERSNAME.S",
                      "NIHDIRENTRYEFFECTIVEDATE": "$elem.NIHDIRENTRYEFFECTIVEDATE.S",
                      "NIHDIRENTRYEXPIRATIONDATE": "$elem.NIHDIRENTRYEXPIRATIONDATE.S",
                      "userAccountControl": "$elem.userAccountControl.S",
                      "USER_ID": "$elem.USER_ID.S",
                      "PERSON_ID": $elem.PERSON_ID.N,
                      "FIRST_NAME": "$elem.FIRST_NAME.S",
                      "LAST_NAME": "$elem.LAST_NAME.S",
                      "NAME_PREFIX": "$elem.NAME_PREFIX.S",
                      "MI_NAME": "$elem.MI_NAME.S",
                      "NAME_SUFFIX": "$elem.NAME_SUFFIX.S",
                      "EMAIL": "$elem.EMAIL.S",
                      "ORG_NAME": "$elem.ORG_NAME.S",
                      "ORG_ID": $elem.ORG_ID.N,
                      "ORG_ADDRESS_1": "$elem.LINE_1_ADDR.S",
                      "ORG_ADDRESS_2": "$elem.LINE_2_ADDR.S",
                      "ORG_ADDRESS_3": "$elem.LINE_3_ADDR.S",
                      "ORG_ADDRESS_4": "$elem.LINE_4_ADDR.S",
                      "ORG_ADDRESS_5": "$elem.LINE_5_ADDR.S",
                      "CITY": "$elem.CITY.S",
                      "STATE": "$elem.STATE.S",
                      "PHONE_NUMBER": "$elem.PHONE_NUMBER.S",
                      "ORG_EMAIL": "$elem.ORG_EMAIL.S",
                      "ACCOUNT_CREATED_DATE": "$elem.ACCOUNT_CREATED_DATE.S",
                      "ACCOUNT_UPDATED_DATE": "$elem.ACCOUNT_UPDATED_DATE.S",
                      "STATUS_CODE": $elem.STATUS_CODE.N,
                      "STATUS_DESC": "$elem.STATUS_DESCRIP.S",
                      "LAST_UPDATED_DAY": "$elem.LAST_UPDATED_DAY.S",
                      "LOGINGOV_USER_ID": "$elem.LOGINGOV_USER_ID.S",
                      "ALIAS_DESCRIP": "$elem.ALIAS_DESCRIP.S"
                    }#if($foreach.hasNext),#end

                #end
                  ]
                }

  /userapi/ned/changesByIc/{ic}:
    get:
      tags:
        - clients
      summary: List NED Changes for the given IC
      operationId: getNEDChangesByIC
      description: |
        List NED Change records that satisfy given IC criteria
      parameters:
        - name: ic
          in: path
          description: IC
          required: true
          schema:
            type: string
            example: 'NCI'
        - name: From_Date
          in: query
          required: false
          schema: 
            type: string
            example: 2022-03-01
        - name: From_Time
          in: query
          required: false
          schema: 
            type: string
            example: 00:00:00
        - name: To_Date
          in: query
          required: false
          schema: 
            type: string
            example: 2022-03-01
        - name: To_Time
          in: query
          required: false
          schema: 
            type: string
            example: 00:00:00
      responses:
        '200':
          $ref: '#/components/responses/ChangesByIcResponse'
      x-amazon-apigateway-integration:
        uri: ${lambda_invoke_arn  }
        httpMethod: POST
        timeoutInMillis: 29000
        type: aws_proxy

components:
  responses: 
    vdsresponse:
      description: Response with a list of VDS User objects
      content:
        application/json:
          schema:
            type: object
            xml:
              wrapped: true
              name: vdsuser
            properties:
              NumberOfRecords:
                type: integer
                description: number of VDS User objects in response
              User:
                type: array
                items:
                  $ref: '#/components/schemas/VDSUser'

    ChangesByIcResponse:
      description: Response with a list of NED Changes records
      content:
        application/json:
          schema:
            type: object
            properties:
              NUMBER_OF_RECORDS:
                type: integer
                description: number of NED Changes records in response
              NED_CHANGES_RECORD:
                type: array
                items:
                  $ref: '#/components/schemas/NEDChangeRecord'

    vdsUsersByIcResponse:
      description: Response with a list of User Records for given IC
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/VDSUsersChunk'

  schemas:

    NEDChangeRecord:
      type: object
      properties:
        NIHSITE:
          type: string
        ACTION_DATE:
          type: string
        ACTION:
          type: string
        UNIQUEIDENTIFIER:
          type: string
        ACTION_TIME:
          type: string
        SN:
          type: string
        NIHORGACRONYM:
          type: string
        GIVENNAME:
          type: string

    VDSUsersChunk:
      type: object
      properties:
        count:
          type: integer
        error:
          type: string
          description: Error message if not empty - rest of the fields are zeros
        lastEvaluatedKey:
          type: string
          description: If present, the result is incomplete, pass this value as "lastEvaluatedKey" query parameter to get the next chunk of results
        items:
          type: array
          items:
            $ref: '#/components/schemas/VDSUser'

    VDSUser:
      type: object
      properties:
        UNIQUEIDENTIFIER:
          type: string
          example: 0011234567
        NIHDUPUID:
          type: string
          example: 0013312345
        NIHADACCTREQ:
          type: string
          example: Y
        NIHSSOUSERNAME:
          type: string
          example: smithj
        distinguishedName:
          type: string
          example: CN=smithj,OU=Users,OU=NCI-Frederick,OU=NIH,OU=AD,DC=nih,DC=gov
        NIHADMAILBOXREQ:
          type: string
          example: Y
        NIHPRIMARYSMTP:
          type: string
          example: johnj@mail.gov
        MAIL:
          type: string
          example: smithj@mail.gov
        proxyAddresses:
          type: array
          items:
            type: string
          example:
            - smtp:smithj@nci.gov
            - X500:/O=NIH/OU=NIHEXCHANGE/cn=Recipients/cn=smithj
            - smtp:smithj@nih.mail.onmicrosoft.com
            - smtp:smithj@nih.gov
        displayName:
          type: string
          example: Smith, John (NIH/NCI) [C]
        PERSONALTITLE:
          type: string
          example: Mr
        GIVENNAME:
          type: string
          example: John
        NIHCOMMONGIVENNAME:
          type: string
          example: John
        NIHNOMIDDLENAME:
          type: string
          example: N
        MIDDLENAME:
          type: string
          example: Joseph
        NIHCOMMONMIDDLENAM:
          type: string
          example: Joseph
        NIHMIXCASESN:
          type: string
          example: Smith Joseph
        NIHMIXCASECOMMONSN:
          type: string
          example: Smith
        SN:
          type: string
          example: Smith
        NIHCOMMONSN:
          type: string
          example: Smith
        GENERATIONQUALIF:
          type: string
          example: Jr
        NIHCOMMONGENQUALIF:
          type: string
          example: Jr
        NIHSUFFIXQUALIFIER:
          type: string
          example: M.D., PH.D.
        TITLE:
          type: string
          example: Board of Scientific Counselor
        NIHIPD:
          type: string
          example: Other
        NIHBADGETITLE:
          type: string
          example: Physician
        NIHIDBADGEEXPDATE:
          type: string
          example: 2026-11-12 00:00:00.0
        NIHSAC:
          type: string
          example: HNCB45
        NIHPrivacyAwarenessCompDate:
          type: string
        PrivacyAwarenessRefresherCompDate:
          type: string
        NIHInformationSecurityAwarenessCompDate:
          type: string
        InformationSecurityRefresherCompDate:
          type: string
        description:
          type: string
          example: This account is Enabled by iam.nih.gov, because the Background Investigation Adjudication is complete, or is in the process of Mailbox creation
        ORGANIZATIONALSTAT:
          type: string
          example: CONTRACTOR
        NIHSUBORGSTATUS:
          type: string
          example: CONTRACTOR
        NIHSUMMERSTATUS:
          type: string
          example: N
        NIHORGPATH:
          type: string
          example: NCI DCTD DTP NPB
        NIHPHYSICALADDRESS:
          type: string
          example: FDC 123 BG RM 119$431 WOOD STREET$FREDERICK MD 21702
        NIHORGACRONYM:
          type: string
          example: NCI
        NIHSERVAO:
          type: string
          example: 0010101234
        MANAGER:
          type: string
          example: 987654321
        NIHCOTRID:
          type: string
          example: 0010123456
        NIHPOC:
          type: string
          example: 0010123456
        NIHCOMPANYNAME:
          type: string
          example: FFRDC FNLCR LBR (Leidos Biomedical Research Inc.)
        NIHCOMPANYPHONE:
          type: string
          example: + 1 111 123 4567
        countryCode:
          type: string
          example: 111
        TELEPHONENUMBER:
          type: string
          example: +1 301 111 1111
        MOBILETELEPHONENUM:
          type: string
          example: +1 301 123 4567
        mobile:
          type: string
          example: 301.123.4567
        ipPhone:
          type: string
          example: (301) 111-1111
        NIHSITE:
          type: string
          example: MD-FCR
        L:
          type: string
          example: Frederick
        BUILDINGNAME:
          type: string
          example: FDC 123
        ROOMNUMBER:
          type: string
          example: 123
        POSTALADDRESS:
          type: string
          example: BG 111 RM 119$1050 BOYLES STREET$FREDERICK MD 21702
        NIHIDBADGELESS6MOS:
          type: string
          example: N
        managedObjects:
          type: string
          example: CN=NCI-Frederick Rees alarms,OU=Distribution Lists,OU=Messaging,OU=NCI-Frederick,OU=NIH,OU=AD,DC=nih,DC=gov
        memberOf:
          type: array
          items:
            type: string
          example:
            - CN=NIH CONTRACTOR ACCOUNTS,OU=NIH WIDE GROUPS,OU=ADOG,DC=nih,DC=gov
            - CN=NIH Exchange Users,OU=Groups,OU=CIT,OU=NIH,ou=ad,dc=nih,dc=gov
            - CN=PrimaryUsers,OU=Accounts,OU=CES,OU=OPS,DC=nih,DC=gov
        NIHCREATETIMESTAMP:
          type: string
          example: 2009-01-14 14:12:30.0
        NIHMODIFYTIMESTAMP:
          type: string
          example: 2021-12-27 10:25:49.0
        NIHMODIFIERSNAME:
          type: string
          example: 123456789
        NIHDIRENTRYEFFECTIVEDATE:
          type: string
          example: 2009-01-14 00:00:00.0
        NIHDIRENTRYEXPIRATIONDATE:
          type: string
          example: 2009-01-14 00:00:00.0
        userAccountControl:
          type: string
          example: 123
