AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Create a dynamodb table 'nedorgs'
Parameters:
  Environment:
    Description: Environment tier
    Type: String
    AllowedValues:
      - dev
      - test
      - qa
      - stage
      - prod
Resources:
  NedorgsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "sac"
          AttributeType: "S"
        -
          AttributeName: "parent_sac"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "parent_sac"
          KeyType: "HASH"
        -
          AttributeName: "sac"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Join
        - '-'
        - - nedorgs
          - !Ref Environment
      GlobalSecondaryIndexes:
        -
          IndexName: sacIndex
          KeySchema:
            -
              AttributeName: "sac"
              KeyType: "HASH"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
          Projection:
            ProjectionType: "ALL"
Outputs:
  DdbNetOrgsArn:
    Description: ARN of nedorgs DynamoDB table
    Value:
      Fn::GetAtt:
        - NedorgsTable
        - Arn
  DdbNetOrgs:
    Description: Nedorgs DynamoDB table name
    Value:
      Ref: NedorgsTable
