AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Create a dynamodb table 'extusers'
Parameters:
  Environment:
    Description: Environment tier
    Type: String
    AllowedValues:
      - dev
      - test
      - qa
      - stage
      - prod
Resources:
  ExtUsersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "USER_ID"
          AttributeType: "S"
        -
          AttributeName: "LAST_UPDATED_DAY"
          AttributeType: "S"
        -
          AttributeName: "LOGINGOV_USER_ID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "USER_ID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Join
        - '-'
        - - extusers
          - !Ref Environment
      GlobalSecondaryIndexes:
        -
          IndexName: dateIndex
          KeySchema:
            -
              AttributeName: "LAST_UPDATED_DAY"
              KeyType: "HASH"
            -
              AttributeName: "USER_ID"
              KeyType: "RANGE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
          Projection:
            ProjectionType: "ALL"
        -
          IndexName: logingovIndex
          KeySchema:
            -
              AttributeName: "LOGINGOV_USER_ID"
              KeyType: "HASH"
            -
              AttributeName: "USER_ID"
              KeyType: "RANGE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
          Projection:
            ProjectionType: "ALL"

Outputs:
  DdbExtusersArn:
    Description: ARN of nextusers DynamoDB table
    Value:
      Fn::GetAtt:
        - ExtUsersTable
        - Arn
  DdbExtusers:
    Description: Extusers DynamoDB table name
    Value:
      Ref: ExtUsersTable
