AWSTemplateFormatVersion: '2010-09-09'
Description: Creates IAM role for API Gateway to access CloudWatch logs; creates IAM role for API Gateway methods to access DynamoDB AWS service
Parameters:
  Environment:
    Description: Environment tier
    Type: String
    AllowedValues:
      - dev
      - test
      - qa
      - stage
      - prod
  DdbTableArn:
    Description: ARN of DynamoDB userinfo table
    Type: String

Resources:
  apiOrgapiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - apigateway-userapi
          - !Ref Environment
          - role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Path: /

  apiAccessDdbRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join
        - '-'
        - - apigateway-userapi-ddb
          - !Ref Environment
          - role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ddbExtusersRead-${Environment}
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ddbPermissions
                Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Ref DdbTableArn
                  - !Sub ${DdbTableArn}/index/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Path: /

  account:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - apiOrgapiRole
          - Arn
Outputs:
  ApiGatewayOrgapiRoleName:
    Description: Name of API Gateway Orgapi role.
    Value:
      Ref: apiOrgapiRole
  ApiGatewayOrgapiRoleArn:
    Description: ARN of API Gateway Orgapi role.
    Value:
      Fn::GetAtt:
      - apiOrgapiRole
      - Arn
  ApiGatewayAccessDdbRoleName:
    Description: Name of API Gateway Access to Dynamo DB role.
    Value:
      Ref: apiAccessDdbRole
  ApiGatewayAccessDdbRoleArn:
    Description: ARN of API Gateway Access to Dynamo DB role.
    Value:
      Fn::GetAtt:
      - apiAccessDdbRole
      - Arn
  ApiGatewayAccount:
    Description: AWS Account that is associated with API Gateway
    Value: !Ref account


