AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Express User Info REST APIs powered by API Gateway and Lambda
Parameters:
  Environment:
    Description: Environment tier
    Type: String
    AllowedValues:
      - dev
      - test
      - qa
      - stage
      - prod
  LambdaRoleArn:
    Description: ARN of lambda function role user api web service
    Type: String
  DynamoDbRoleArn:
    Description: ARN of Api Gateway permission to access DynamoDB role.  Used in swagger file
    Type: String
  S3bucket:
    Description: S3 bucket for Lambda Auth and UserApi code
    Type: String
  Issuer:
    Description: Okta Authentication Server URL
    Type: String
  Audience:
    Description: Okta Authentication audience
    Type: String
    Default: api://default
  UsersTableName:
    Description: Users table name
    Type: String

Resources:
  EraCommonsUserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ../aws-cf-scripts/swagger-userapi-v2.yaml
      Auth:
        DefaultAuthorizer: TokenAuthorizer
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt AuthFunction.Arn
        ResourcePolicy:
          CustomStatements:
            -
              Effect: "Allow"
              Principal: "*"
              Action: "execute-api:Invoke"
              Resource:
                - "execute-api:/*/*/*"
            -
              Effect: "Deny"
              Principal: "*"
              Action: "execute-api:Invoke"
              Resource:
                - "execute-api:/*/*/*"
              Condition:
                NotIpAddress:
                  aws:SourceIp:
                    - 128.231.0.0/16
      EndpointConfiguration:
        Type: REGIONAL
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: true
          LoggingLevel: INFO
      TracingEnabled: true

  EraCommonsUserApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: >-
        Lambda function contains eRA Commons External Users Info REST APIs implementation.
      FunctionName: !Join
        - '-'
        - - lambda-era-commons-user-api
          - !Ref Environment
      CodeUri:
        Bucket: !Ref S3bucket
        Key: lambda-userapi.zip
      Handler: src/lambda.handler
      Runtime: nodejs12.x
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          LOG_LEVEL: info
      Tags:
        app : userinfoapi
      Role: !Ref LambdaRoleArn
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref EraCommonsUserApi
            Path: /eracommonsapi/v1/users
            Method: GET
        GetUserById:
          Type: Api
          Properties:
            RestApiId: !Ref EraCommonsUserApi
            Path: /eracommonsapi/v1/user/{userID}
            Method: GET
        GetUserByDate:
          Type: Api
          Properties:
            RestApiId: !Ref EraCommonsUserApi
            Path: /eracommonsapi/v1/users/date/{date}
            Method: GET

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: >-
        Lambda function with basic authorization.
      FunctionName: !Join
        - '-'
        - - lambda-auth
          - !Ref Environment
      CodeUri:
        Bucket: !Ref S3bucket
        Key: lambda-auth.zip
      Handler: src/lambda.handler
      Runtime: nodejs12.x
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          LOG_LEVEL: info
          AUDIENCE: !Ref Audience
          ISSUER: !Ref Issuer
      Tags:
        app : userinfoapi
      Role: !Ref LambdaRoleArn

Outputs:
  LambdaFunctionConsoleUrl:
    Description: Console URL for the Lambda Function.
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${EraCommonsUserApiLambdaFunction}

  ApiGatewayApiConsoleUrl:
    Description: Console URL for the API Gateway API's Stage.
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/apis/${EraCommonsUserApi}/stages/${Environment}

  ApiUrl:
    Description: Invoke URL for your API. Clicking this link will perform a GET request
      on the root resource of your API.
    Value: !Sub https://${EraCommonsUserApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/

  LambdaFunctionName:
    Description: Name of the Serverless Express Lambda Function
    Value: !Ref EraCommonsUserApiLambdaFunction

  ApiHostName:
    Description: Host name with root folder to create URL for your API.
    Value: !Sub ${EraCommonsUserApi}.execute-api.${AWS::Region}.amazonaws.com
