/**
 * User REST Web Service API
 * Enterprise Data & Integration Services Web Services - **NED REST Web Service**
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: NCICBIITBizAppsSupportLowTier@mail.nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NEDChangeRecord } from './nEDChangeRecord';

export class GetNEDChangesByIC200Response {
    /**
    * number of NED Changes records in response
    */
    public NUMBER_OF_RECORDS?: number;
    public NED_CHANGES_RECORD?: Array<NEDChangeRecord>;

    public static example(): GetNEDChangesByIC200Response {
        let r = new GetNEDChangesByIC200Response();
        r.NUMBER_OF_RECORDS = 1
        r.NED_CHANGES_RECORD = new Array<NEDChangeRecord>()
        r.NED_CHANGES_RECORD.push(NEDChangeRecord.example())
        return r;
    }
    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nUMBEROFRECORDS",
            "baseName": "NUMBER_OF_RECORDS",
            "type": "number"
        },
        {
            "name": "nEDCHANGESRECORD",
            "baseName": "NED_CHANGES_RECORD",
            "type": "Array<NEDChangeRecord>"
        }    ];

    static getAttributeTypeMap() {
        return GetNEDChangesByIC200Response.attributeTypeMap;
    }
}

