/**
 * User REST Web Service API
 * Enterprise Data & Integration Services Web Services - **NED REST Web Service**
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: NCICBIITBizAppsSupportLowTier@mail.nih.gov
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { VDSUser } from './vDSUser';

export class GetVDSUserByNIHId200Response {
    /**
    * number of VDS User objects in response
    */
    'numberOfRecords'?: number;
    'user'?: Array<VDSUser>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numberOfRecords",
            "baseName": "NumberOfRecords",
            "type": "number"
        },
        {
            "name": "user",
            "baseName": "User",
            "type": "Array<VDSUser>"
        }    ];

    static getAttributeTypeMap() {
        return GetVDSUserByNIHId200Response.attributeTypeMap;
    }
}

