# This is a basic workflow to help you get started with Actions

name: Remote Repo - Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      host-runner:
        description: 'Selected self hosted (nci-self-hosted) of github hosted () runner'
        required: true
        type: string
        default: 'ubuntu-latest'

  workflow_call: 
    inputs:
      host-runner:
        description: 'Selected self hosted (nci-self-hosted) of github hosted () runner'
        required: true
        type: string
        default: 'ubuntu-latest'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.host-runner }}
    
    permissions:
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repository Checkout
        uses: actions/checkout@v3
        with: 
          repository: CBIIT/app-edis

      - name: generate swagger file
        working-directory: generate-ts-swagger
        run: |
          npm run swagger

      - name: build lambda zip file
        working-directory: generate-ts-swagger
        run: |
          npm run zip-prod

      #Store the created zip files as artifacts
      - name: store-artifacts
        working-directory: generate-ts-swagger
        uses: actions/upload-artifact@v3
        with:
          name: generate-ts-swagger
          path: |
            ./out/*.*
