# This is a basic workflow to help you get started with Actions

name: 3.03 - Deploy API Gateway into stage
run-name: 3.03 - Deploy API Gateway ${{ inputs.apiid }} into stage - ${{ inputs.stage }}

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      envt:
        description: 'Environment'
        required: true
        default: dev
      stage:
        description: 'Stage'
        required: true
        default: dev
      apiid:
        description: 'API Gateway - REST API ID'
        required: true
      descr:
        description: 'Description'
        required: true
        default: '"eadis-userinfo-dev auto deployment"'
      host-runner:
        type: string
        required: false
        description: 'Selected self hosted (nci-self-hosted) of github hosted () runner'
        default: 'ubuntu-latest'

jobs:
  deployment:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.host-runner }}

    environment: ${{ inputs.envt }}

    permissions:
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup AWS configuration
        env:
          OIDC_ROLE: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}
        if: "${{ env.OIDC_ROLE != '' }}"
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}
          role-session-name: TestSessionWithOIDC
          aws-region: us-east-1

      - name: Create API Gateway deployment
        run: |
          aws apigateway create-deployment --rest-api-id ${{ inputs.apiid }} --stage-name ${{ inputs.stage }} --description ${{ inputs.descr }}
