# This is a basic workflow to help you get started with Actions

name: eRA Commons - Deploy 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      envt:
        description: 'Environment'
        required: true
        default: dev
      tier:
        description: 'Deployment tier'
        required: true
        default: dev2
      s3bucket:
        description: 'S3 bucket to use for deployment'
        required: true
        default: cf-templates-woyzwinjenjf-us-east-1
      subnet1:
        description: 'VPC Subnet 1 id'
        required: true
      subnet2:
        description: 'VPC Subnet 2 id'
        required: true
      vpcsg:
        description: 'VPC Security Group id'
        required: true

jobs:
  deployment:
    
    # The type of runner that the job will run on
    uses: ./.github/workflows/deploy-tf-template.yml
    with:
      envt: ${{ github.event.inputs.envt }}
      tier: ${{ github.event.inputs.tier }}
      s3bucket: ${{ github.event.inputs.s3bucket }}
      subnet1: ${{ github.event.inputs.subnet1 }}
      subnet2: ${{ github.event.inputs.subnet2 }}
      vpcsg: ${{ github.event.inputs.vpcsg }}
      build-eracommons: true
      build-userinfo: false
    secrets: inherit

    permissions:
      packages: write
      id-token: write
      contents: write

