# This is a basic workflow to help you get started with Actions

name: Remote Repo - Deploy w artifacts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      envt:
        description: 'Environment'
        required: true
        type: string
        default: dev
      tier:
        description: 'Deployment tier'
        required: true
        type: string
        default: dev2
      s3bucket:
        description: 'S3 bucket to use for deployment'
        required: true
        type: string
        default: cf-templates-woyzwinjenjf-us-east-1
      subnet1:
        description: 'VPC Subnet 1 id'
        required: true
        type: string
      subnet2:
        description: 'VPC Subnet 2 id'
        required: true
        type: string
      vpcsg:
        description: 'VPC Security Group id'
        required: true
        type: string
      artifact_repo:
        description: 'Artifacts Build repo'
        default: CBIIT/app-edis
        required: true
        type: string
      artifact_workflow:
        description: 'Artifacts Build Workflow yml'
        default: build-remote-test.yml
        required: true
        type: string
      artifact_build:
        description: 'Artifacts Build Workflow number'
        required: true
        type: string
      artifact_name:
        description: 'Artifacts name'
        default: edis-built
        required: true
        type: string
      host-runner:
        description: 'Selected self hosted (nci-self-hosted) of github hosted () runner'
        required: true
        type: string
        default: 'ubuntu-latest'

  workflow_call: 
    inputs:
      envt:
        description: 'Environment'
        required: true
        type: string
        default: dev
      tier:
        description: 'Deployment tier'
        required: true
        type: string
        default: dev2
      s3bucket:
        description: 'S3 bucket to use for deployment'
        required: true
        type: string
        default: cf-templates-woyzwinjenjf-us-east-1
      subnet1:
        description: 'VPC Subnet 1 id'
        required: true
        type: string
      subnet2:
        description: 'VPC Subnet 2 id'
        required: true
        type: string
      vpcsg:
        description: 'VPC Security Group id'
        required: true
        type: string
      artifact_repo:
        description: 'Artifacts Build repo'
        default: CBIIT/app-edis
        required: true
        type: string
      artifact_workflow:
        description: 'Artifacts Build Workflow yml'
        default: build-remote-test.yml
        required: true
        type: string
      artifact_build:
        description: 'Artifacts Build Workflow number'
        required: true
        type: string
      artifact_name:
        description: 'Artifacts name'
        default: edis-built
        required: true
        type: string
      host-runner:
        description: 'Selected self hosted (nci-self-hosted) of github hosted () runner'
        required: true
        type: string
        default: 'ubuntu-latest'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.host-runner }}
    
    environment: ${{ inputs.envt }}

    permissions:
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repository Checkout
        uses: actions/checkout@v3
        with: 
          repository: CBIIT/app-edis

      - name: download pre-built resources
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ inputs.artifacts_workflow }}
          workflow_conclusion: success
          repo: ${{ inputs.artifacts_repo }}
          run_number: ${{ inputs.artifact_build }}
          name: ${{ inputs.artifact_name }}
      
      # Runs a set of commands using the runners shell
      - name: Workflow Parameters
        run: |
          echo Environment - ${{ inputs.envt }}
          echo Deployment Tier - ${{ inputs.tier }}
          echo S3 Bucket - ${{ inputs.s3bucket }}
          echo Subnet 1 - ${{ inputs.subnet1 }}
          echo Subnet 2 - ${{ inputs.subnet2 }}
          echo Security Group - ${{ inputs.vpcsg }}
          echo Secret - ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}

      #      - name: generate swagger file
#        working-directory: generate-ts-swagger
#        run: |
#          npm run swagger
#
#      - name: build lambda zip file
#        working-directory: generate-ts-swagger
#        run: |
#          npm run zip-prod

      - name: Setup AWS configuration
        env: 
          OIDC_ROLE: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}
        if: "${{ env.OIDC_ROLE != '' }}"
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}
          role-session-name: TestSessionWithOIDC
          aws-region: us-east-1

      - name: Install Terraform
        id: install
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_wrapper: false
      
      - name: Init Terraform 
        id: init
        run: terraform init -backend-config="bucket=${{ inputs.s3bucket }}" -backend-config="key=api-edis-tf-state/api-edis-generate-ts-${{ inputs.tier }}" -backend-config="region=us-east-1"
        working-directory: generate-ts-swagger/deploy_w_artifacts/

      - name: Validate Terraform
        id: validate
        run: terraform validate
        working-directory: generate-ts-swagger/deploy_w_artifacts/

      - name: Planning Terraform
        id: plan
        run: terraform plan -var 'env=${{ inputs.tier }}' -var 'subnet1=${{ inputs.subnet1 }}' -var 'subnet2=${{ inputs.subnet2 }}' -var 'vpcsg=${{ inputs.vpcsg }}'
        working-directory: generate-ts-swagger/deploy_w_artifacts/

      - name: Terraform Deployment
        id: apply
        run: terraform apply -auto-approve -input=false -lock=false -var 'env=${{ inputs.tier }}' -var 'subnet1=${{ inputs.subnet1 }}' -var 'subnet2=${{ inputs.subnet2 }}' -var 'vpcsg=${{ inputs.vpcsg }}'
        working-directory: generate-ts-swagger/deploy_w_artifacts/
