# This is a basic workflow to help you get started with Actions

name: AWS account wide - Deploy 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      envt:
        description: 'Environment'
        required: true
        default: dev
      s3bucket:
        description: 'S3 bucket to use for deployment'
        required: true
        default: cf-templates-woyzwinjenjf-us-east-1

jobs:
  deployment:
    
    # The type of runner that the job will run on
    uses: ./.github/workflows/deploy-tf-template.yml
    with:
      envt: ${{ github.event.inputs.envt }}
      tier: "account-wide"
      s3bucket: ${{ github.event.inputs.s3bucket }}
      subnet1: "na-subnet1"
      subnet2: "na-suvnet2"
      vpcsg: "na-vpcsg"
      build-eracommons: false
      build-userinfo: false
    secrets: inherit

    permissions:
      packages: write
      id-token: write
      contents: write

