# This is a basic workflow to help you get started with Actions

name: Sumologic Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
      tier:
        description: 'Environment tier'
        required: true
        default: dev
      s3bucket:
        description: 'S3 bucket to use for deployment'
        required: true
        default: cf-templates-woyzwinjenjf-us-east-1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: ${{ github.event.inputs.tier }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Input Parameters
        run: |
          echo environment secrets ${{ secrets.AWS_ACCESS_KEY_ID }} and ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          echo Environment Tier - ${{ github.event.inputs.tier }}
          echo S3 Bucket - ${{ github.event.inputs.s3bucket }}
      
      - name: Setup AWS configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Sumologic sam deployment
        working-directory: install-scripts
        run: |
          ./sam-deploy-sumologic-no-profile.sh -a ${{ github.event.inputs.s3bucket }} -t ${{ github.event.inputs.tier }}