# This is a basic workflow to help you get started with Actions

name: Terraform - README docs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "document"
  document:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: ${{ github.event.inputs.envt }}

    permissions:
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: TerraDocs Execute
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: tf,tf/modules/api-gateway,tf/modules/ddb-extusers,tf/modules/lambda
          output-file: README.md
          output-method: inject
          git-push: "true"  