# This is a basic workflow to help you get started with Actions

name: _Test OIDC provider - STAGE

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
          tier:
            description: 'Environment tier'
            required: true
            default: dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.tier }}
    
    permissions: 
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup AWS configuration
        env:
          OIDC_ROLE: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}
        if: "${{ env.OIDC_ROLE != '' }}"
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}
          role-session-name: TestSessionWithOIDC
          aws-region: us-east-1
          
      - name: Test AWS Configuration
        run: |
          aws cloudformation describe-stacks | grep StackName

      - name: Init Terraform
        id: initEraCommons
        env:
          TF_LOG: DEBUG
        run: terraform init -backend-config="bucket=cf-templates-1lzxjjk6zocca-us-east-1" -backend-config="key=api-edis-tf-state/eracommons-stage" -backend-config="region=us-east-1"
        working-directory: tf-eracommons/
