# This is a basic workflow to help you get started with Actions

name: _Test Secrets Manager get
run-name: _Test Secrets Manager get - ${{ inputs.tier }}

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
          tier:
            description: 'Environment tier'
            required: true
            default: dev

          secret:
            description: 'Secrets name'
            required: true

          key:
            description: 'Secret key'
            required: false
            default: ''

          val:
            description: 'Secret value'
            required: false
            default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.tier }}
    
    permissions: 
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      - name: Setup AWS configuration
        env:
          OIDC_ROLE: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}
        if: "${{ env.OIDC_ROLE != '' }}"
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_PROVIDER_ROLE }}
          role-session-name: TestSessionWithOIDC
          aws-region: us-east-1
          
      - name: Get the secret key/value into variable
        id: secret-string
        if: "${{ inputs.key != '' }}"
        run: |
          IKEY=${{inputs.key}}
          IVALUE=${{inputs.val}}
          echo "$IKEY $IVALUE"
          JSONCONTENT="$(aws secretsmanager get-secret-value --secret-id ${{ inputs.secret }} | jq '.SecretString | fromjson' |  jq ".$IKEY=\"$IVALUE\"")"
          echo "$JSONCONTENT"
          echo "ss_env=$JSONCONTENT" >> $GITHUB_ENV
          echo "Next command..."

      - name: Print the variable
        if: "${{ inputs.key != '' }}"
        run: |
          echo ${{ steps.secret-string.outputs.ss }} | jq '.'

      - name: Get the secret all key/values into variable
        id: secret-string
        if: "${{ inputs.key == '' }}"
        run: |
          JSONCONTENT="$(aws secretsmanager get-secret-value --secret-id ${{ inputs.secret }} | jq '.SecretString')"
          echo "$JSONCONTENT"
          echo "ss_out=$JSONCONTENT" >> $GITHUB_OUTPUT
#          echo "Next command..."

# echo "ss=$(aws secretsmanager get-secret-value --secret-id ${{ inputs.secret }} | jq '.SecretString')" >> $GITHUB_OUTPUT

