# This is a basic workflow to help you get started with Actions

name: Remote Repo - Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      host-runner:
        description: 'Selected self hosted (nci-self-hosted) of github hosted () runner'
        required: true
        type: string
        default: 'ubuntu-latest'
      run_id:
        description: 'Run ID'
        required: false
        type: string
        default: ''
      run_number:
        description: 'Run Number'
        required: false
        type: string
        default: ''
        


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.host-runner }}
    
    permissions:
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: download pre-built resources by run id
        uses: dawidd6/action-download-artifact@v2
        if: (inputs.run_id != '')
        with:
          workflow_conclusion: success
          repo: CBIIT/app-edis
          run_id: ${{ inputs.run_id }}
          
      - name: download pre-built resources by build number
        uses: dawidd6/action-download-artifact@v2
        if: (inputs.build_number != '')
        with:
          workflow_conclusion: success
          repo: CBIIT/app-edis
          workflow: build-remote-test.yml
          run_number: ${{ inputs.run_number }}
          
      - name: Display artifacts
        run: ls -R
