# This is a basic workflow to help you get started with Actions

name: _Test Download artifacts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      envt:
        description: 'Environment'
        required: true
        default: dev
      build_id:
        description: 'Build Run ID'
        required: true
        type: string
      host-runner:
        description: 'Selected self hosted (nci-self-hosted) of github hosted () runner'
        required: true
        type: string
        default: 'ubuntu-latest'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.host-runner }}
    
    environment: ${{ inputs.envt }}

    permissions:
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#      - name: Repository Checkout
#        uses: actions/checkout@v4

      - name: Workflow Inputs
        run: |
          echo ${{ github.event.client_payload.body }}

      - name: download pre-built resources by run id
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          run_id: ${{ inputs.build_id }}
          github_token: ${{ secrets.PUBLISH_TOKEN }}

      - name: Display artifacts
        run: ls -R
