# This is a basic workflow to help you get started with Actions

name: Remote Repo - Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      host-runner:
        description: 'Selected self hosted (nci-self-hosted) of github hosted () runner'
        required: true
        type: string
        default: 'ubuntu-latest'
      workflow:
        description: 'Build Workflow yml'
        default: build-remote-test.yml
        required: true
        type: string
      build_number:
        description: 'Build Workflow number'
        required: false
        type: string


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.host-runner }}
    
    permissions:
      packages: write
      id-token: write
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repository Checkout
        uses: actions/checkout@v3
        with: 
          repository: CBIIT/app-edis

      - name: download pre-built resources
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ inputs.workflow }}
          workflow_conclusion: success
          repo: CBIIT/app-edis
          run_number: ${{ inputs.build_number }}
          name: edis-built
          
      - name: Display artifacts
        run: ls -R
